POST http://localhost:8080/events
content-type: application/json

{
    "name": "Test event 2",
    "description": "A test event 2",
    "location": "A test location 2",
    "dateTime": "2025-01-01T15:30:00.000Z"
}