PUT http://localhost:8080/events/1
content-type: application/json

{
    "name": "Updated event",
    "description": "Updated description",
    "location": "Updated location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}